CONTRIBUTING.md
README.md

Addresses Issue #7 
Update `contributions.md` to include team norms, git workflow, and best practices

[Issue #7] Update the Contributions Guide

---

back-end/app.js

Set up backend

---

front-end/src/pages/App.jsx
front-end/src/pages/User.jsx
front-end/src/pages/Wait.css
front-end/src/pages/Wait.jsx

Addresses Issue #59 
This PR creates the waiting room page users will redirect to when waiting for other group members.

#59 Create Waiting Room

---

back-end/README.md
back-end/app.js
back-end/package-lock.json
back-end/package.json
back-end/test/app.test.js
back-end/utils/add.js
package-lock.json
package.json

This pull requests adds the scripts, testing libraries, and documentation for our backend API. Closes #90 
To run both the frontend and backend at the same time use the command 
First, install dependencies in front-end and back-end using npm install
Then: `npm run dev` 
To run tests on our backend:
`cd back-end && npm run test`
Check test coverage
`cd back-end && npm run coverage`
The react application runs on port 3000 and the API server now runs on port 8000. Going to localhost:8000 should show test, and localhost:3000 should show the homepage.

#90: Add testing libraries + npm scripts

---

back-end/app.js
back-end/package-lock.json
back-end/package.json
front-end/src/components/RoomButton.jsx
front-end/src/pages/CreateRoom.jsx
front-end/src/pages/InviteCode.jsx
front-end/src/utils/api.js

This PR closes #77. 
To connect the backend with the frontend, a new environment variable called REACT_APP_API_SERVER has been created with http://localhost:8000 as the default value. 
In addition, cors and uuid have been added as backend dependencies to make it easier to generate unique IDs, and fix control-origin errors that occur. 
A new endpoint POST /room has been created which contains a name, location, and capacity, and stores the values in app.locals.rooms until a database is set up.
https://user-images.githubusercontent.com/36852809/140453109-d68beb8c-4ea7-41ac-ba20-4b62524df736.mov
Please merge #90 first, and chase base to master before merging

#77: Generate invite code for create group

---

front-end/src/pages/App.jsx
front-end/src/pages/RandomCuisine.css
front-end/src/pages/RandomCuisine.jsx

This addresses issue #54. 
The page isn't linked to any other pages yet because when I created it the other pages weren't made yet

Created random cuisine page

---

front-end/src/pages/App.jsx
front-end/src/pages/PreferredDish.css
front-end/src/pages/PreferredDish.jsx

Addresses Issue #56
Instead of using radio buttons, which limit users to one choice, I changed it so that it's checkboxes. That way, we could possibly have _more_ restaurant recommendations for the user.
**NOTE**: This uses the skipbutton component in the `dietary-restrictions` branch so there will be errors until that branch is merged.

#56 Add preferred dishes page

---

back-end/app.js
back-end/data/restauraunts.json
back-end/data/user_preference.json
back-end/test/loss_function.test.js
back-end/utils/loss_function.js

Closes #74. This PR implements a basic ranking algorithm to determine if a restaurant is a good match for a user. In the data folder are mock restaurant results from the documenu API, which will be implemented at a later date. We test the generate_restuaraunts_map and loss_function to make sure that they return the expected result for the two users.
Also adds a TODO for GET /restauraunts which is currently blocked until we set up documenu and capture the required data from users.

#74: Implement loss function

---

back-end/app.js
back-end/models/group.js
back-end/models/user.js
back-end/package-lock.json
back-end/package.json
back-end/utils/database.js

Our MongoDB cluster has been created. This PR sets up  the required modules for using the DB (eg. mongoose, dotenv) and adds a boilerplate structure for our schemas (which will be implemented in #104.
**Notes**
- I've added a basic route `/` that adds an object to the DB. This is just a test and can be deleted in a future PR. 
- Will send out the `.env` our backend relies on in slack. 
- Everyone should have been added as a project owner for our mongodb cluster. Let me know if that isn't the case.

Set up MongoDB

---

back-end/app.js
back-end/models/group.js
back-end/models/user.js

This PR sets up the schemas we will use to add user and group objects to the db. There are test routes available to see the db insertion in action: `/new-group`, `/new-user`. These are temporary and should be deleted once the actual implementation is done. 
**Note**: This should be merged in after #102. The DB URI is on slack.

#104 Set up mongoose schemas

---

back-end/app.js
front-end/src/pages/CreateRoom.jsx

This PR stores the group details provided by the user during the group creation phase. 
**SHOULD BE MERGED IN AFTER #115** 
**Note**: Since we are storing `longitude`, `latitude` points in the DB for location, that means the google's autocomplete search will fail (for now). There will be fixed once #101 is completed. So for now, please stick to using the current location feature.

#105 Store Group Details in DB

---

front-end/src/pages/CreateRoom.jsx

Converts google address selected from search to lat/lng coordinates, which will be stored in the database.
Changes for this PR are located in `front-end/src/pages/CreateRoom.jsx`
**NOTE**: Should be merged after all the other DB PRs that are open

#101 Fix Google Search

---

back-end/app.js
back-end/package.json
back-end/test/app.test.js
back-end/utils/database.js
front-end/src/pages/App.test.js
front-end/src/pages/CreateRoom.jsx
front-end/src/pages/JoinRoom.css
front-end/src/pages/JoinRoom.jsx
front-end/src/utils/validation.js

This PR validates the invite code provided by the user, making sure it exists in the DB. 
**NOTE**: Should be merged after everything else. All changes in this PR are in the latest commit `validate invite code`. 
https://user-images.githubusercontent.com/21044058/141717854-7011dff4-6c86-416a-9c56-91851631f734.mov

#117 Validate Invite Code

---

back-end/app.js
back-end/routes/documenu.js
back-end/routes/restaurant.js
back-end/routes/room.js
back-end/routes/user.js
back-end/test/app.test.js
back-end/utils/database.js
front-end/src/pages/JoinRoom.jsx
front-end/src/pages/User.jsx
package-lock.json
package.json

Addresses issue #136 
This PR initializes the express-router, creates a router directory, and groups routes into separate files. In this way, our `app.js` file is less cluttered.
**NOTE**: This should be merged in after #117

#136 Use Express Router

---

back-end/app.js
back-end/package-lock.json
back-end/package.json
back-end/test/app.test.js
back-end/utils/database.js
front-end/package-lock.json

Fixes buggy unit tests that only worked locally and not on circleCI. Turns out, we needed to mock our DB :) 
NOTE: should be merged in after #117 and #137

Update Unit Tests

---

INSTALLATION.md

Updates the installation docs to include the latest commands

#123: Update installation docs

---

back-end/app.js
back-end/models/group.js
back-end/package-lock.json
back-end/package.json
back-end/routes/documenu.js
back-end/routes/room.js
back-end/test/app.test.js
front-end/src/components/CuisineItem.jsx
front-end/src/components/Input.jsx
front-end/src/pages/App.jsx
front-end/src/pages/ChooseCuisine.jsx
front-end/src/pages/CreateRoom.jsx
front-end/src/pages/CuisineVote.jsx
front-end/src/pages/Error.css
front-end/src/pages/Error.jsx
front-end/src/pages/JoinRoom.css
front-end/src/pages/PreferredDish.css
front-end/src/pages/PreferredDish.jsx
front-end/src/pages/PreferredDishInitial.css
front-end/src/pages/PreferredDishInitial.jsx
front-end/src/pages/RandomCuisine.jsx
front-end/src/pages/User.css
front-end/src/pages/User.jsx

This PR uses the Documenu API to fetch dishes within the group's geolocation and relating to the cuisine. Also does some minor fixes, like added the price range to the DB and more error handling.
I needed to create a separate **keyword** screen since even though documenu doesn't require it, without the search parameter the dishes that were returned had nothing to do with the cuisine.
**Note**: Should be merged in after #73. Also, there is no db storage in this PR since it will be addressed by #107 
**Enter Search Keyword**
**Error if no keyword is provided**
**Error screen if no results are found**
**Results for keyword `cheese` and cuisine `italian`**

#125 Populate Dishes for Dish preferences

---

back-end/app.js
back-end/models/group.js
back-end/routes/cuisine.js
back-end/routes/random.js
front-end/package-lock.json
front-end/src/pages/ChooseCuisine.jsx
front-end/src/pages/RandomCuisine.jsx

Storing votes

---

.dockerignore
INSTALLATION.md
back-end/Dockerfile
front-end/Dockerfile

Allows us to use docker, see installation instructions for more details. Closes #149
TODO: Implement deployment in #151

#149: Add Dockerfile

---

back-end/routes/documenu.js
front-end/src/pages/PreferredDish.css
front-end/src/pages/PreferredDish.jsx
front-end/src/pages/RandomCuisine.jsx

This PR allows the user to view a description of the dish and be able to reset their "search keyword". Additionally, it filters out the menu item # in the dish name e.g. `01. Fried chicken`
**NOTE**: Should be merged in after #107

Preferred Dish UI and other bug fixes

---

front-end/src/components/HomePageLogo.css
front-end/src/pages/CuisineVote.css
front-end/src/pages/CuisineVote.jsx
front-end/src/pages/PreferredDishInitial.css
front-end/src/pages/PreferredDishInitial.jsx
front-end/src/pages/RestaurantDetails.css
front-end/src/pages/RestaurantDetails.jsx
front-end/src/pages/ResultsPage.css
front-end/src/pages/ResultsPage.jsx
front-end/src/pages/WinningCuisine.css
front-end/src/pages/WinningCuisine.jsx

This PR makes modifications to our UI like removing placeholder text, styling, bugs, etc.

#148 UI Cleanup

---

README.md

Adds the circle CI build icon, our banner, and a link to the hosted version of the app.

150: Update Readme

---

README.md

#164: Update readme

---

back-end/package-lock.json
back-end/package.json
back-end/routes/cuisine.js
back-end/routes/dishes.js
back-end/routes/documenu.js
back-end/routes/restaurant.js
back-end/routes/room.js
back-end/routes/user.js
back-end/routes/wait.js

Closes #122, Uses the express-validator module prior to sending any data originating from the request to the database.

#122: Use express validator

---

back-end/routes/restaurant.js

fix restaurants list from 50 to 100

Fix backend issue

---

back-end/routes/cuisine.js

Add callback fns to queries so that saving cuisine votes work again

Fix: Add callback to db queries

---

back-end/routes/restaurant.js
back-end/routes/room.js
back-end/routes/win.js
front-end/src/pages/JoinRoom.jsx
front-end/src/pages/PreferredDish.jsx
front-end/src/pages/WinningCuisine.jsx

Final commit

---

back-end/Dockerfile
back-end/package-lock.json
front-end/Dockerfile
front-end/ecosystem.config.js
front-end/package-lock.json

Currently, our deployment is crashing and will not restart. Using PM2, we should be able to automatically reboot the server. In addition, we now run our frontend in production mode. Errors on the frontend will no longer show. The script has also been modified so that a failing docker kill command will no longer stop the deployment.

Improve docker stability with pm2

---

back-end/routes/win.js
front-end/src/pages/WinningCuisine.jsx

Fix picking winning cuising multiple times to once.

Fix routing bug

---

front-end/src/pages/PreferredDish.jsx
front-end/src/pages/PreferredDishInitial.jsx

Closes #179.  This fixes the skip button that prematurely redirects the user to the final page. Currently, the skip button will automatically skip the user to the results page. We want it so that it will redirect the user to the waiting room.

#179: Fix skip button

---

back-end/routes/restaurant.js
back-end/utils/loss_function.js
front-end/src/components/ResultsCell.css
front-end/src/components/ResultsCell.jsx
front-end/src/pages/RestaurantDetails.jsx
front-end/src/pages/ResultsPage.jsx

- Fix /win routing
- restaurant fetch
- Restaurant
- Fix misspelling

Fix Restaurant fetch

---

front-end/src/pages/CreateRoom.css
front-end/src/pages/CreateRoom.jsx
front-end/src/pages/JoinRoom.css
front-end/src/pages/PreferredDish.jsx
front-end/src/pages/RestaurantDetails.css
front-end/src/pages/RestaurantDetails.jsx
front-end/src/pages/TeamPage.jsx

**Restaurant Details**
**Join Room**
**Create Room**

Fix css styles & add back button to Restaurant Details
